Param()

Write-Host "🚀 Quick deploy (Windows) starting..."

# Copy environment and config files if they don't exist
if (-Not (Test-Path ".env") -and (Test-Path ".env.example")) {
  Copy-Item ".env.example" ".env"
  Write-Host "📄 Created .env from .env.example"
}
if (-Not (Test-Path "config.json") -and (Test-Path "config.json.example")) {
  Copy-Item "config.json.example" "config.json"
  Write-Host "📄 Created config.json from config.json.example"
}

Write-Host "⚠️  WARNING: Using default configuration from .env.example!"
Write-Host "🔒 For production deployment, please manually update the following values in .env:"
Write-Host "   - DATA_ENCRYPTION_KEY"
Write-Host "   - JWT_SECRET"
Write-Host "   - Any other secrets or API keys"
Write-Host ""

# Generate key material (RSA + AES master key) via Go if available; fallback to backend auto-generation
$go = Get-Command go -ErrorAction SilentlyContinue
if ($go) {
  Write-Host "🔑 Generating keys via 'go run ./cmd/genkeys'"
  & go run ./cmd/genkeys
} else {
  Write-Host "⚠️  Go not found; keys will be auto-generated by backend on first start"
}

# Build and start services
Write-Host "🏗️  Building containers..."
docker compose build
Write-Host "▶️  Starting containers..."
docker compose up -d

Write-Host "✅ Deployment complete! Web interface should be available at http://localhost:3000"
Write-Host "💡 Use 'docker compose logs -f' to view logs"