#!/bin/bash
set -e

echo "🚀 Quick deploy (macOS) starting..."

# Copy .env file from example if it doesn't exist
if [ ! -f .env ] && [ -f .env.example ]; then
  cp .env.example .env
  echo "📄 Created .env from .env.example"
fi

echo "⚠️  WARNING: Using default configuration from .env.example!"
echo "🔒 For production deployment, please manually update the following values in .env:"
echo "   - DATA_ENCRYPTION_KEY"
echo "   - JWT_SECRET"
echo "   - Any other secrets or API keys"
echo ""

# Copy config.json if it doesn't exist
[ ! -f config.json ] && [ -f config.json.example ] && cp config.json.example config.json && echo "📄 Created config.json from config.json.example"

# Generate key material (RSA + AES master key) if Go is available; otherwise backend will generate on first run
if command -v go >/dev/null 2>&1; then
  echo "🔑 Generating keys via go run ./cmd/genkeys"
  go run ./cmd/genkeys
else
  echo "⚠️  Go not found; keys will be auto-generated by backend on first start"
fi

# Build and start services
echo "🏗️  Building containers (with PostgreSQL)..."
docker compose build
echo "▶️  Starting containers..."
docker compose up -d

echo "✅ Deployment complete! Web interface should be available at http://localhost:3000"
echo "💡 Use 'docker compose logs -f' to view logs"
if ! grep -q '^DATABASE_URL=' .env 2>/dev/null; then
  echo "ℹ️  DATABASE_URL not set in .env; backend will use default: postgres://postgres:postgres@postgres:5432/nofx?sslmode=disable"
fi
